<?php
/**
 * Avalanche for Magento 1.6+
 * Designed by Fast Division (http://fastdivision.com)
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file license.txt.
 * It is also available through the world-wide-web at this URL:
 * http://fastdivision.com/legal/license.txt
 *
 * @author     Fast Division
 * @version    1.3.0
 * @copyright  Copyright 2012 Fast Division
 * @license    http://fastdivision.com/legal/license.txt
 */
?>
	<meta http-equiv="Content-Type" content="<?php echo $this->getContentType() ?>">
	<title><?php echo $this->getTitle() ?></title>
	<meta name="description" content="<?php echo htmlspecialchars($this->getDescription()) ?>">
	<meta name="keywords" content="<?php echo htmlspecialchars($this->getKeywords()) ?>">
	<meta name="robots" content="<?php echo htmlspecialchars($this->getRobots()) ?>">
	<link rel="shortcut icon" href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>media/favicon/<?php echo Mage::getStoreConfig('avalanche_config/avalanche_design/avalanche_favicon') ?>">
	<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('css/style.css') ?>" media="all" />
	<script src="//ajax.googleapis.com/ajax/libs/prototype/1.7.0.0/prototype.js"></script>
	<?php echo $this->getCssJsHtml() ?>
	<?php echo $this->getChildHtml() ?>
	<?php echo $this->getIncludes() ?>
	<?php $googleFonts = Mage::helper('themeconfig')->getGoogleFonts(); ?>
	<?php if($googleFonts != ''): ?>
	<link href="//fonts.googleapis.com/css?family=<?php echo $googleFonts ?>" rel="stylesheet" type="text/css">
	<?php endif; ?>