<?php
/**
 * Avalanche for Magento 1.6+
 * Designed by Fast Division (http://fastdivision.com)
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file license.txt.
 * It is also available through the world-wide-web at this URL:
 * http://fastdivision.com/legal/license.txt
 *
 * @author     Fast Division
 * @version    1.3.0
 * @copyright  Copyright 2012 Fast Division
 * @license    http://fastdivision.com/legal/license.txt
 */
?>
<div class="grid_12 white-box">
    <h1><?php echo $this->__('Customer Login') ?></h1>

	<div class="page-messages">
 		<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
	</div>

    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="login-form" class="site-form">
		<div class="grid_6 omega">
			<h3><?php echo $this->__('Registered Customers') ?></h3>
			
			<div class="inner-box">
               <p><?php echo $this->__('If you have an account with us, please log in.') ?></p>
               <ul class="form-list">
                   <li class="field">
                       <label for="email" class="required"><?php echo $this->__('Email') ?><em>*</em></label>
                       <div class="input-box">
                           <input type="text" name="login[username]" value="<?php echo $this->htmlEscape($this->getUsername()) ?>" id="email" class="input-text required-entry validate-email" title="<?php echo $this->__('Email Address') ?>" />
                       </div>
                   </li>
                   <li class="field">
                       <label for="pass" class="required"><?php echo $this->__('Password') ?><em>*</em></label>
                       <div class="input-box">
                           <input type="password" name="login[password]" class="input-text required-entry validate-password" id="pass" title="<?php echo $this->__('Password') ?>" />
                       </div>
                   </li>
               </ul>

               <button type="submit" class="action-button action-button-no-arrow" title="<?php echo $this->__('Login') ?>" name="send" id="send2"><span><?php echo $this->__('Login') ?></span></button>&nbsp;&nbsp;
               <a href="<?php echo $this->getForgotPasswordUrl() ?>" class="small"><?php echo $this->__('Forgot Your Password?') ?></a><br/><br/>
			</div>
		</div>
		<div class="grid_6 omega">
			<h3><?php echo $this->__('New Customers') ?></h3>
			
			<div class="inner-box">
               <p><?php echo $this->__('By creating an account with our store, you will be able to move through the checkout process faster, store multiple shipping addresses, view and track your orders in your account and more.') ?></p>
               <button type="button" title="<?php echo $this->__('Create an Account') ?>" class="button" onclick="window.location='<?php echo $this->getCreateAccountUrl() ?>';"><span><span><?php echo $this->__('Create an Account') ?></span></span></button>
			</div>
		</div>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('login-form', true);
    //]]>
    </script>
</div>
