<?php
/**
 * Avalanche for Magento 1.6+
 * Designed by Fast Division (http://fastdivision.com)
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file license.txt.
 * It is also available through the world-wide-web at this URL:
 * http://fastdivision.com/legal/license.txt
 *
 * @author     Fast Division
 * @version    1.3.0
 * @copyright  Copyright 2012 Fast Division
 * @license    http://fastdivision.com/legal/license.txt
 */
?>
<div class="grid_12 white-box">
    <h1><?php echo $this->__('Reset a Password'); ?></h1>

	<div class="white-box-inner">
		<?php echo $this->getMessagesBlock()->getGroupedHtml(); ?>
		<form action="<?php echo $this->getUrl('*/*/resetpasswordpost', array('_query' => array('id' => $this->getCustomerId(), 'token' => $this->getResetPasswordLinkToken()))); ?>" method="post" id="form-validate">
		    <div class="fieldset">
		        <ul class="form-list">
		            <li>
	                    <label for="password" class="required"><?php echo $this->__('New Password'); ?><em>*</em></label>
	                    <div class="input-box">
	                        <input type="password" class="input-text required-entry validate-password" name="password" id="password" />
	                    </div><br/>
	
				        <label for="confirmation" class="required"><?php echo $this->__('Confirm New Password'); ?><em>*</em></label>
	                    <div class="input-box">
	                        <input type="password" class="input-text required-entry validate-cpassword" name="confirmation" id="confirmation" />
	                    </div>
		            </li>
		        </ul>
		    </div>
		    <div class="buttons-set">
		        <button type="submit" title="<?php echo $this->__('Reset a Password'); ?>" class="action-button"><span><?php echo $this->__('Reset a Password'); ?></span></button>
		    </div>
		</form>
		<script type="text/javascript">
		/*<![CDATA[*/
		    var dataForm = new VarienForm('form-validate', true);
		/*]]>*/
		</script>
	</div>
</div>