<?php
/**
 * Avalanche Mobile for Magento 1.6+
 * Designed by Fast Division (http://fastdivision.com)
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file license.txt.
 * It is also available through the world-wide-web at this URL:
 * http://fastdivision.com/legal/license.txt
 *
 * @author     Fast Division
 * @version    1.0.0
 * @copyright  Copyright 2012 Fast Division
 * @license    http://fastdivision.com/legal/license.txt
 */
?>
<div class="white-box">
    <h1><?php echo Mage::helper('customer')->__('Logged Out') ?></h1>

	<div class="white-box-inner">
		<p><?php echo Mage::helper('customer')->__('You have logged out and will be redirected to our homepage in 5 seconds.') ?></p>
		<script type="text/javascript">
		//<![CDATA[
		    setTimeout(function(){ location.href = '<?php echo $this->getUrl() ?>'},5000);
		//]]>
		</script>
	</div>
</div>