<?php
/**
 * Avalanche for Magento 1.6+
 * Designed by Fast Division (http://fastdivision.com)
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file license.txt.
 * It is also available through the world-wide-web at this URL:
 * http://fastdivision.com/legal/license.txt
 *
 * @author     Fast Division
 * @version    1.3.0
 * @copyright  Copyright 2012 Fast Division
 * @license    http://fastdivision.com/legal/license.txt
 */
?>
<table id="details-table" class="data-table">
    <?php if ($this->helper('tax')->displayCartBothPrices()): $colspan = $rowspan = 2; else: $colspan = $rowspan = 1; endif; ?>
    <col />
    <col width="1" />
    <col width="1" />
    <col width="1" />
    <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
    <col width="1" />
    <col width="1" />
    <?php endif; ?>
    <thead>
        <tr>
            <th rowspan="<?php echo $rowspan ?>" class="a-center"><?php echo $this->__('Qty') ?></th>
            <th>&nbsp;</th>
            <th rowspan="<?php echo $rowspan ?>" width="60%"><?php echo $this->__('Product Name') ?></th>
            <th colspan="<?php echo $colspan ?>" class="a-center"><?php echo $this->__('Price') ?></th>
            <th colspan="<?php echo $colspan ?>" class="a-center"><?php echo $this->__('Subtotal') ?></th>
        </tr>
        <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
            <tr>
                <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
            </tr>
        <?php endif; ?>
    </thead>
    <?php echo $this->getChildHtml('totals'); ?>
    <tbody>
        <?php foreach($this->getItems() as $_item): ?>
            <?php echo $this->getItemHtml($_item) ?>
        <?php endforeach ?>
    </tbody>
</table>