<?php
/**
 * Avalanche for Magento 1.6+
 * Designed by Fast Division (http://fastdivision.com)
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file license.txt.
 * It is also available through the world-wide-web at this URL:
 * http://fastdivision.com/legal/license.txt
 *
 * @author     Fast Division
 * @version    1.3.0
 * @copyright  Copyright 2012 Fast Division
 * @license    http://fastdivision.com/legal/license.txt
 */
?>

<?php /* @var $this Mage_Sales_Block_Recurring_Profiles */ ?>

<div class="white-box">
    <h1><?php echo $this->__('Recurring Profiles') ?></h1>

	<div class="white-box-inner">
		<div class="page-messages">
			<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
		</div>

		<div class="recurring-profiles">
		    <?php echo $this->getChildHtml('grid')?>
		</div>
	</div>
	
	<div class="box-action">
        <p class="back-link"><a href="<?php echo $this->escapeHtml($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
    </div>
</div>
