<?php
/**
 * Avalanche for Magento 1.6+
 * Designed by Fast Division (http://fastdivision.com)
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file license.txt.
 * It is also available through the world-wide-web at this URL:
 * http://fastdivision.com/legal/license.txt
 *
 * @author     Fast Division
 * @version    1.3.0
 * @copyright  Copyright 2012 Fast Division
 * @license    http://fastdivision.com/legal/license.txt
 */
?>
<?php
$_item = $this->getItem();
$isVisibleProduct = $_item->getProduct()->isVisibleInSiteVisibility();
?>
<tr>
	<td class="item-photo">
		<?php if ($this->hasProductUrl()):?><a href="<?php echo $this->getProductUrl() ?>" title="<?php echo $this->htmlEscape($this->getProductName()) ?>" class="product-image"><?php endif;?><img src="<?php echo $this->getProductThumbnail()->resize(50); ?>" width="50" height="50" alt="<?php echo $this->htmlEscape($this->getProductName()) ?>" /><?php if ($this->hasProductUrl()):?></a><?php endif;?>
	</td>
    <td>
        <div class="item-desc">
	        <?php if ($this->hasProductUrl()):?>
	            <a href="<?php echo $this->getProductUrl() ?>"><?php echo $this->htmlEscape($this->getProductName()) ?></a>
	        <?php else: ?>
	            <?php echo $this->htmlEscape($this->getProductName()) ?>
	        <?php endif; ?>
			<div class="item-detail">
				<?php if ($_options = $this->getOptionList()):?>
		        <div class="item-options">
		            <?php foreach ($_options as $_option) : ?>
		            	<?php $_formattedOptionValue = $this->getFormatedOptionValue($_option) ?>
		            	<?php echo $this->htmlEscape($_option['label']) ?>: <?php echo $_formattedOptionValue['value'] ?><br>
		            <?php endforeach; ?>
		        </div>
		        <?php endif;?>
		
		        <?php if ($messages = $this->getMessages()): ?>
		        <?php foreach ($messages as $message): ?>
		            <p class="item-msg <?php echo $message['type'] ?>">* <?php echo $message['text'] ?></p>
		        <?php endforeach; ?>
		        <?php endif; ?>
		        <?php if ($addtInfoBlock = $this->getProductAdditionalInformationBlock()):?>
		            <?php echo $addtInfoBlock->setItem($_item)->toHtml() ?>
		        <?php endif;?>
			</div>
		</div>
	</td>
	<td class="center">
		<?php echo $this->getQty() ?>
	</td>
</tr>