<?php
/**
 * Avalanche for Magento 1.6+
 * Designed by Fast Division (http://fastdivision.com)
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file license.txt.
 * It is also available through the world-wide-web at this URL:
 * http://fastdivision.com/legal/license.txt
 *
 * @author     Fast Division
 * @version    1.3.0
 * @copyright  Copyright 2012 Fast Division
 * @license    http://fastdivision.com/legal/license.txt
 */
?>
<div id="cart" class="clearfix">
	<div class="grid_12 white-box">
		<h1><?php echo $this->__('Shopping Cart is Empty') ?></h1>
		
		<div class="white-box-inner">
			<div class="cart-empty">
				<div class="page-messages">
			    	<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
				</div>
			    <p><?php echo $this->__('You have no items in your shopping cart.') ?></p>
			    <p><?php echo $this->__('Click <a href="%s">here</a> to continue shopping.', $this->getContinueShoppingUrl()) ?></p>
			</div>
		</div>
	</div>
</div>