<?php
/**
 * Avalanche for Magento 1.6+
 * Designed by Fast Division (http://fastdivision.com)
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file license.txt.
 * It is also available through the world-wide-web at this URL:
 * http://fastdivision.com/legal/license.txt
 *
 * @author     Fast Division
 * @version    1.3.0
 * @copyright  Copyright 2012 Fast Division
 * @license    http://fastdivision.com/legal/license.txt
 */
?>
<div class="page-title">
    <h1><?php echo $this->__('Wishlist') ?></h1>
</div>
<?php if($wishlist->getSize()): ?>
<form action="<?php echo $this->getUrl('customer/wishlist/updatePost') ?>" method="post">
    <table class="data-table">
        <col />
        <col width="60" />
        <col width="60" />
        <col width="60" />
        <thead>
            <tr>
                <th><?php echo $this->__('Product') ?></th>
                <th><?php echo $this->__('Status') ?></th>
                <th><?php echo $this->__('To Cart') ?></th>
                <th><?php echo $this->__('Remove') ?></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach($wishlist as $item): ?>
            <tr>
                <td>
                    <input type="hidden" value="1" name="wishlist[<?php echo $item->getItemId() ?>]" />
                    <a href="<?php echo $this->getUrl('catalog/product/view/id/'.$item->getProduct()->getId()) ?>"><?php echo $this->htmlEscape($item->getProduct()->getName()) ?></a>
                </td>
                <td><?php echo $item->getStatus() ?></td>
                <td><input type="checkbox" value="1" name="to_cart[<?php echo $item->getItemId() ?>]" class="checkbox" /></td>
                <td><input type="checkbox" value="1" name="remove[<?php echo $item->getItemId() ?>]" class="checkbox" /></td>
            </tr>
        <?php endforeach ?>
        </tbody>
    </table>
    <div class="buttons-set">
        <a href="<?php echo Mage::getBaseUrl() ?>">&laquo; <?php echo $this->__('Continue Shopping') ?></a>
        <input type="submit" value="<?php echo $this->__('Update') ?>" class="input-button" name="do" />
    </div>
</form>
<?php else: ?>
    <p><?php echo $this->__('You have placed no products yet.') ?></p>
    <div class="buttons-set">
        <p class="back-link"><a href="<?php echo $this->getUrl('customer/account') ?>"><small>&laquo; </small><?php echo $this->__('Back - link to the previously viewed page') ?></a></p>
    </div>
<?php endif ?>
