<?php
/**
 * Avalanche for Magento 1.6+
 * Designed by Fast Division (http://fastdivision.com)
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file license.txt.
 * It is also available through the world-wide-web at this URL:
 * http://fastdivision.com/legal/license.txt
 *
 * @author     Fast Division
 * @version    1.3.0
 * @copyright  Copyright 2012 Fast Division
 * @license    http://fastdivision.com/legal/license.txt
 */

class FastDivision_ThemeConfig_Model_FontHeader {
    public function toOptionArray() {
        return array(
			array('value'=>'Helvetica/Arial', 'label'=>Mage::helper('themeconfig')->__('Helvetica, Arial')),
			array('value'=>'Lucida Grande/Calibri/Arial', 'label'=>Mage::helper('themeconfig')->__('Lucida Grande, Calibri, Arial')),
			array('value'=>'Abel', 'label'=>Mage::helper('themeconfig')->__('Abel')),
			array('value'=>'Abril Fatface', 'label'=>Mage::helper('themeconfig')->__('Abril Fatface')),
			array('value'=>'Aclonica', 'label'=>Mage::helper('themeconfig')->__('Aclonica')),
			array('value'=>'Acme', 'label'=>Mage::helper('themeconfig')->__('Acme')),
			array('value'=>'Actor', 'label'=>Mage::helper('themeconfig')->__('Actor')),
			array('value'=>'Adamina', 'label'=>Mage::helper('themeconfig')->__('Adamina')),
			array('value'=>'Aguafina Script', 'label'=>Mage::helper('themeconfig')->__('Aguafina Script')),
			array('value'=>'Aladin', 'label'=>Mage::helper('themeconfig')->__('Aladin')),
			array('value'=>'Aldrich', 'label'=>Mage::helper('themeconfig')->__('Aldrich')),
			array('value'=>'Alex Brush', 'label'=>Mage::helper('themeconfig')->__('Alex Brush')),
			array('value'=>'Alfa Slab One', 'label'=>Mage::helper('themeconfig')->__('Alfa Slab One')),
			array('value'=>'Alice', 'label'=>Mage::helper('themeconfig')->__('Alice')),
			array('value'=>'Alike', 'label'=>Mage::helper('themeconfig')->__('Alike')),
			array('value'=>'Alike Angular', 'label'=>Mage::helper('themeconfig')->__('Alike Angular')),
			array('value'=>'Allan', 'label'=>Mage::helper('themeconfig')->__('Allan')),
			array('value'=>'Allerta', 'label'=>Mage::helper('themeconfig')->__('Allerta')),
			array('value'=>'Allerta Stencil', 'label'=>Mage::helper('themeconfig')->__('Allerta Stencil')),
			array('value'=>'Almendra', 'label'=>Mage::helper('themeconfig')->__('Almendra')),
			array('value'=>'Almendra SC', 'label'=>Mage::helper('themeconfig')->__('Almendra SC')),
			array('value'=>'Amaranth', 'label'=>Mage::helper('themeconfig')->__('Amaranth')),
			array('value'=>'Amatic SC', 'label'=>Mage::helper('themeconfig')->__('Amatic SC')),
			array('value'=>'Andada', 'label'=>Mage::helper('themeconfig')->__('Andada')),
			array('value'=>'Andika', 'label'=>Mage::helper('themeconfig')->__('Andika')),
			array('value'=>'Angkor', 'label'=>Mage::helper('themeconfig')->__('Angkor')),
			array('value'=>'Annie Use Your Telescope', 'label'=>Mage::helper('themeconfig')->__('Annie Use Your Telescope')),
			array('value'=>'Anonymous Pro', 'label'=>Mage::helper('themeconfig')->__('Anonymous Pro')),
			array('value'=>'Antic', 'label'=>Mage::helper('themeconfig')->__('Antic')),
			array('value'=>'Anton', 'label'=>Mage::helper('themeconfig')->__('Anton')),
			array('value'=>'Arapey', 'label'=>Mage::helper('themeconfig')->__('Arapey')),
			array('value'=>'Arbutus', 'label'=>Mage::helper('themeconfig')->__('Arbutus')),
			array('value'=>'Architects Daughter', 'label'=>Mage::helper('themeconfig')->__('Architects Daughter')),
			array('value'=>'Arimo', 'label'=>Mage::helper('themeconfig')->__('Arimo')),
			array('value'=>'Arizonia', 'label'=>Mage::helper('themeconfig')->__('Arizonia')),
			array('value'=>'Armata', 'label'=>Mage::helper('themeconfig')->__('Armata')),
			array('value'=>'Artifika', 'label'=>Mage::helper('themeconfig')->__('Artifika')),
			array('value'=>'Arvo', 'label'=>Mage::helper('themeconfig')->__('Arvo')),
			array('value'=>'Asset', 'label'=>Mage::helper('themeconfig')->__('Asset')),
			array('value'=>'Astloch', 'label'=>Mage::helper('themeconfig')->__('Astloch')),
			array('value'=>'Asul', 'label'=>Mage::helper('themeconfig')->__('Asul')),
			array('value'=>'Atomic Age', 'label'=>Mage::helper('themeconfig')->__('Atomic Age')),
			array('value'=>'Aubrey', 'label'=>Mage::helper('themeconfig')->__('Aubrey')),
			array('value'=>'Bad Script', 'label'=>Mage::helper('themeconfig')->__('Bad Script')),
			array('value'=>'Balthazar', 'label'=>Mage::helper('themeconfig')->__('Balthazar')),
			array('value'=>'Bangers', 'label'=>Mage::helper('themeconfig')->__('Bangers')),
			array('value'=>'Basic', 'label'=>Mage::helper('themeconfig')->__('Basic')),
			array('value'=>'Battambang', 'label'=>Mage::helper('themeconfig')->__('Battambang')),
			array('value'=>'Baumans', 'label'=>Mage::helper('themeconfig')->__('Baumans')),
			array('value'=>'Bayon', 'label'=>Mage::helper('themeconfig')->__('Bayon')),
			array('value'=>'Belgrano', 'label'=>Mage::helper('themeconfig')->__('Belgrano')),
			array('value'=>'Bentham', 'label'=>Mage::helper('themeconfig')->__('Bentham')),
			array('value'=>'Bevan', 'label'=>Mage::helper('themeconfig')->__('Bevan')),
			array('value'=>'Bigshot One', 'label'=>Mage::helper('themeconfig')->__('Bigshot One')),
			array('value'=>'Bilbo', 'label'=>Mage::helper('themeconfig')->__('Bilbo')),
			array('value'=>'Bilbo Swash Caps', 'label'=>Mage::helper('themeconfig')->__('Bilbo Swash Caps')),
			array('value'=>'Bitter', 'label'=>Mage::helper('themeconfig')->__('Bitter')),
			array('value'=>'Black Ops One', 'label'=>Mage::helper('themeconfig')->__('Black Ops One')),
			array('value'=>'Bokor', 'label'=>Mage::helper('themeconfig')->__('Bokor')),
			array('value'=>'Bonbon', 'label'=>Mage::helper('themeconfig')->__('Bonbon')),
			array('value'=>'Boogaloo', 'label'=>Mage::helper('themeconfig')->__('Boogaloo')),
			array('value'=>'Bowlby One', 'label'=>Mage::helper('themeconfig')->__('Bowlby One')),
			array('value'=>'Bowlby One SC', 'label'=>Mage::helper('themeconfig')->__('Bowlby One SC')),
			array('value'=>'Brawler', 'label'=>Mage::helper('themeconfig')->__('Brawler')),
			array('value'=>'Bree Serif', 'label'=>Mage::helper('themeconfig')->__('Bree Serif')),
			array('value'=>'Bubblegum Sans', 'label'=>Mage::helper('themeconfig')->__('Bubblegum Sans')),
			array('value'=>'Buda', 'label'=>Mage::helper('themeconfig')->__('Buda')),
			array('value'=>'Buenard', 'label'=>Mage::helper('themeconfig')->__('Buenard')),
			array('value'=>'Butcherman', 'label'=>Mage::helper('themeconfig')->__('Butcherman')),
			array('value'=>'Cabin', 'label'=>Mage::helper('themeconfig')->__('Cabin')),
			array('value'=>'Cabin Condensed', 'label'=>Mage::helper('themeconfig')->__('Cabin Condensed')),
			array('value'=>'Cabin Sketch', 'label'=>Mage::helper('themeconfig')->__('Cabin Sketch')),
			array('value'=>'Caesar Dressing', 'label'=>Mage::helper('themeconfig')->__('Caesar Dressing')),
			array('value'=>'Cagliostro', 'label'=>Mage::helper('themeconfig')->__('Cagliostro')),
			array('value'=>'Calligraffitti', 'label'=>Mage::helper('themeconfig')->__('Calligraffitti')),
			array('value'=>'Cambo', 'label'=>Mage::helper('themeconfig')->__('Cambo')),
			array('value'=>'Candal', 'label'=>Mage::helper('themeconfig')->__('Candal')),
			array('value'=>'Cantarell', 'label'=>Mage::helper('themeconfig')->__('Cantarell')),
			array('value'=>'Cardo', 'label'=>Mage::helper('themeconfig')->__('Cardo')),
			array('value'=>'Carme', 'label'=>Mage::helper('themeconfig')->__('Carme')),
			array('value'=>'Carter One', 'label'=>Mage::helper('themeconfig')->__('Carter One')),
			array('value'=>'Caudex', 'label'=>Mage::helper('themeconfig')->__('Caudex')),
			array('value'=>'Cedarville Cursive', 'label'=>Mage::helper('themeconfig')->__('Cedarville Cursive')),
			array('value'=>'Ceviche One', 'label'=>Mage::helper('themeconfig')->__('Ceviche One')),
			array('value'=>'Changa One', 'label'=>Mage::helper('themeconfig')->__('Changa One')),
			array('value'=>'Chango', 'label'=>Mage::helper('themeconfig')->__('Chango')),
			array('value'=>'Chenla', 'label'=>Mage::helper('themeconfig')->__('Chenla')),
			array('value'=>'Cherry Cream Soda', 'label'=>Mage::helper('themeconfig')->__('Cherry Cream Soda')),
			array('value'=>'Chewy', 'label'=>Mage::helper('themeconfig')->__('Chewy')),
			array('value'=>'Chicle', 'label'=>Mage::helper('themeconfig')->__('Chicle')),
			array('value'=>'Chivo', 'label'=>Mage::helper('themeconfig')->__('Chivo')),
			array('value'=>'Coda', 'label'=>Mage::helper('themeconfig')->__('Coda')),
			array('value'=>'Coda Caption', 'label'=>Mage::helper('themeconfig')->__('Coda Caption')),
			array('value'=>'Comfortaa', 'label'=>Mage::helper('themeconfig')->__('Comfortaa')),
			array('value'=>'Coming Soon', 'label'=>Mage::helper('themeconfig')->__('Coming Soon')),
			array('value'=>'Concert One', 'label'=>Mage::helper('themeconfig')->__('Concert One')),
			array('value'=>'Content', 'label'=>Mage::helper('themeconfig')->__('Content')),
			array('value'=>'Contrail One', 'label'=>Mage::helper('themeconfig')->__('Contrail One')),
			array('value'=>'Convergence', 'label'=>Mage::helper('themeconfig')->__('Convergence')),
			array('value'=>'Cookie', 'label'=>Mage::helper('themeconfig')->__('Cookie')),
			array('value'=>'Copse', 'label'=>Mage::helper('themeconfig')->__('Copse')),
			array('value'=>'Corben', 'label'=>Mage::helper('themeconfig')->__('Corben')),
			array('value'=>'Cousine', 'label'=>Mage::helper('themeconfig')->__('Cousine')),
			array('value'=>'Coustard', 'label'=>Mage::helper('themeconfig')->__('Coustard')),
			array('value'=>'Covered By Your Grace', 'label'=>Mage::helper('themeconfig')->__('Covered By Your Grace')),
			array('value'=>'Crafty Girls', 'label'=>Mage::helper('themeconfig')->__('Crafty Girls')),
			array('value'=>'Creepster', 'label'=>Mage::helper('themeconfig')->__('Creepster')),
			array('value'=>'Crete Round', 'label'=>Mage::helper('themeconfig')->__('Crete Round')),
			array('value'=>'Crimson Text', 'label'=>Mage::helper('themeconfig')->__('Crimson Text')),
			array('value'=>'Crushed', 'label'=>Mage::helper('themeconfig')->__('Crushed')),
			array('value'=>'Cuprum', 'label'=>Mage::helper('themeconfig')->__('Cuprum')),
			array('value'=>'Damion', 'label'=>Mage::helper('themeconfig')->__('Damion')),
			array('value'=>'Dancing Script', 'label'=>Mage::helper('themeconfig')->__('Dancing Script')),
			array('value'=>'Dangrek', 'label'=>Mage::helper('themeconfig')->__('Dangrek')),
			array('value'=>'Dawning of a New Day', 'label'=>Mage::helper('themeconfig')->__('Dawning of a New Day')),
			array('value'=>'Days One', 'label'=>Mage::helper('themeconfig')->__('Days One')),
			array('value'=>'Delius', 'label'=>Mage::helper('themeconfig')->__('Delius')),
			array('value'=>'Delius Swash Caps', 'label'=>Mage::helper('themeconfig')->__('Delius Swash Caps')),
			array('value'=>'Delius Unicase', 'label'=>Mage::helper('themeconfig')->__('Delius Unicase')),
			array('value'=>'Devonshire', 'label'=>Mage::helper('themeconfig')->__('Devonshire')),
			array('value'=>'Didact Gothic', 'label'=>Mage::helper('themeconfig')->__('Didact Gothic')),
			array('value'=>'Dorsa', 'label'=>Mage::helper('themeconfig')->__('Dorsa')),
			array('value'=>'Dr Sugiyama', 'label'=>Mage::helper('themeconfig')->__('Dr Sugiyama')),
			array('value'=>'Droid Sans', 'label'=>Mage::helper('themeconfig')->__('Droid Sans')),
			array('value'=>'Droid Sans Mono', 'label'=>Mage::helper('themeconfig')->__('Droid Sans Mono')),
			array('value'=>'Droid Serif', 'label'=>Mage::helper('themeconfig')->__('Droid Serif')),
			array('value'=>'Duru Sans', 'label'=>Mage::helper('themeconfig')->__('Duru Sans')),
			array('value'=>'Dynalight', 'label'=>Mage::helper('themeconfig')->__('Dynalight')),
			array('value'=>'EB Garamond', 'label'=>Mage::helper('themeconfig')->__('EB Garamond')),
			array('value'=>'Eater', 'label'=>Mage::helper('themeconfig')->__('Eater')),
			array('value'=>'Electrolize', 'label'=>Mage::helper('themeconfig')->__('Electrolize')),
			array('value'=>'Engagement', 'label'=>Mage::helper('themeconfig')->__('Engagement')),
			array('value'=>'Enriqueta', 'label'=>Mage::helper('themeconfig')->__('Enriqueta')),
			array('value'=>'Expletus Sans', 'label'=>Mage::helper('themeconfig')->__('Expletus Sans')),
			array('value'=>'Fanwood Text', 'label'=>Mage::helper('themeconfig')->__('Fanwood Text')),
			array('value'=>'Fascinate', 'label'=>Mage::helper('themeconfig')->__('Fascinate')),
			array('value'=>'Fascinate Inline', 'label'=>Mage::helper('themeconfig')->__('Fascinate Inline')),
			array('value'=>'Federant', 'label'=>Mage::helper('themeconfig')->__('Federant')),
			array('value'=>'Federo', 'label'=>Mage::helper('themeconfig')->__('Federo')),
			array('value'=>'Fjord One', 'label'=>Mage::helper('themeconfig')->__('Fjord One')),
			array('value'=>'Flamenco', 'label'=>Mage::helper('themeconfig')->__('Flamenco')),
			array('value'=>'Flavors', 'label'=>Mage::helper('themeconfig')->__('Flavors')),
			array('value'=>'Fondamento', 'label'=>Mage::helper('themeconfig')->__('Fondamento')),
			array('value'=>'Fontdiner Swanky', 'label'=>Mage::helper('themeconfig')->__('Fontdiner Swanky')),
			array('value'=>'Forum', 'label'=>Mage::helper('themeconfig')->__('Forum')),
			array('value'=>'Francois One', 'label'=>Mage::helper('themeconfig')->__('Francois One')),
			array('value'=>'Freehand', 'label'=>Mage::helper('themeconfig')->__('Freehand')),
			array('value'=>'Fresca', 'label'=>Mage::helper('themeconfig')->__('Fresca')),
			array('value'=>'Frijole', 'label'=>Mage::helper('themeconfig')->__('Frijole')),
			array('value'=>'Fugaz One', 'label'=>Mage::helper('themeconfig')->__('Fugaz One')),
			array('value'=>'GFS Didot', 'label'=>Mage::helper('themeconfig')->__('GFS Didot')),
			array('value'=>'GFS Neohellenic', 'label'=>Mage::helper('themeconfig')->__('GFS Neohellenic')),
			array('value'=>'Galdeano', 'label'=>Mage::helper('themeconfig')->__('Galdeano')),
			array('value'=>'Gentium Basic', 'label'=>Mage::helper('themeconfig')->__('Gentium Basic')),
			array('value'=>'Gentium Book Basic', 'label'=>Mage::helper('themeconfig')->__('Gentium Book Basic')),
			array('value'=>'Geo', 'label'=>Mage::helper('themeconfig')->__('Geo')),
			array('value'=>'Geostar', 'label'=>Mage::helper('themeconfig')->__('Geostar')),
			array('value'=>'Geostar Fill', 'label'=>Mage::helper('themeconfig')->__('Geostar Fill')),
			array('value'=>'Give You Glory', 'label'=>Mage::helper('themeconfig')->__('Give You Glory')),
			array('value'=>'Gloria Hallelujah', 'label'=>Mage::helper('themeconfig')->__('Gloria Hallelujah')),
			array('value'=>'Goblin One', 'label'=>Mage::helper('themeconfig')->__('Goblin One')),
			array('value'=>'Gochi Hand', 'label'=>Mage::helper('themeconfig')->__('Gochi Hand')),
			array('value'=>'Goudy Bookletter 1911', 'label'=>Mage::helper('themeconfig')->__('Goudy Bookletter 1911')),
			array('value'=>'Gravitas One', 'label'=>Mage::helper('themeconfig')->__('Gravitas One')),
			array('value'=>'Gruppo', 'label'=>Mage::helper('themeconfig')->__('Gruppo')),
			array('value'=>'Habibi', 'label'=>Mage::helper('themeconfig')->__('Habibi')),
			array('value'=>'Hammersmith One', 'label'=>Mage::helper('themeconfig')->__('Hammersmith One')),
			array('value'=>'Handlee', 'label'=>Mage::helper('themeconfig')->__('Handlee')),
			array('value'=>'Hanuman', 'label'=>Mage::helper('themeconfig')->__('Hanuman')),
			array('value'=>'Herr Von Muellerhoff', 'label'=>Mage::helper('themeconfig')->__('Herr Von Muellerhoff')),
			array('value'=>'Holtwood One SC', 'label'=>Mage::helper('themeconfig')->__('Holtwood One SC')),
			array('value'=>'Homemade Apple', 'label'=>Mage::helper('themeconfig')->__('Homemade Apple')),
			array('value'=>'IM Fell DW Pica', 'label'=>Mage::helper('themeconfig')->__('IM Fell DW Pica')),
			array('value'=>'IM Fell DW Pica SC', 'label'=>Mage::helper('themeconfig')->__('IM Fell DW Pica SC')),
			array('value'=>'IM Fell Double Pica', 'label'=>Mage::helper('themeconfig')->__('IM Fell Double Pica')),
			array('value'=>'IM Fell Double Pica SC', 'label'=>Mage::helper('themeconfig')->__('IM Fell Double Pica SC')),
			array('value'=>'IM Fell English', 'label'=>Mage::helper('themeconfig')->__('IM Fell English')),
			array('value'=>'IM Fell English SC', 'label'=>Mage::helper('themeconfig')->__('IM Fell English SC')),
			array('value'=>'IM Fell French Canon', 'label'=>Mage::helper('themeconfig')->__('IM Fell French Canon')),
			array('value'=>'IM Fell French Canon SC', 'label'=>Mage::helper('themeconfig')->__('IM Fell French Canon SC')),
			array('value'=>'IM Fell Great Primer', 'label'=>Mage::helper('themeconfig')->__('IM Fell Great Primer')),
			array('value'=>'IM Fell Great Primer SC', 'label'=>Mage::helper('themeconfig')->__('IM Fell Great Primer SC')),
			array('value'=>'Iceland', 'label'=>Mage::helper('themeconfig')->__('Iceland')),
			array('value'=>'Inconsolata', 'label'=>Mage::helper('themeconfig')->__('Inconsolata')),
			array('value'=>'Inder', 'label'=>Mage::helper('themeconfig')->__('Inder')),
			array('value'=>'Indie Flower', 'label'=>Mage::helper('themeconfig')->__('Indie Flower')),
			array('value'=>'Irish Grover', 'label'=>Mage::helper('themeconfig')->__('Irish Grover')),
			array('value'=>'Istok Web', 'label'=>Mage::helper('themeconfig')->__('Istok Web')),
			array('value'=>'Italianno', 'label'=>Mage::helper('themeconfig')->__('Italianno')),
			array('value'=>'Jockey One', 'label'=>Mage::helper('themeconfig')->__('Jockey One')),
			array('value'=>'Josefin Sans', 'label'=>Mage::helper('themeconfig')->__('Josefin Sans')),
			array('value'=>'Josefin Slab', 'label'=>Mage::helper('themeconfig')->__('Josefin Slab')),
			array('value'=>'Judson', 'label'=>Mage::helper('themeconfig')->__('Judson')),
			array('value'=>'Julee', 'label'=>Mage::helper('themeconfig')->__('Julee')),
			array('value'=>'Jura', 'label'=>Mage::helper('themeconfig')->__('Jura')),
			array('value'=>'Just Another Hand', 'label'=>Mage::helper('themeconfig')->__('Just Another Hand')),
			array('value'=>'Just Me Again Down Here', 'label'=>Mage::helper('themeconfig')->__('Just Me Again Down Here')),
			array('value'=>'Kameron', 'label'=>Mage::helper('themeconfig')->__('Kameron')),
			array('value'=>'Kelly Slab', 'label'=>Mage::helper('themeconfig')->__('Kelly Slab')),
			array('value'=>'Kenia', 'label'=>Mage::helper('themeconfig')->__('Kenia')),
			array('value'=>'Khmer', 'label'=>Mage::helper('themeconfig')->__('Khmer')),
			array('value'=>'Knewave', 'label'=>Mage::helper('themeconfig')->__('Knewave')),
			array('value'=>'Koulen', 'label'=>Mage::helper('themeconfig')->__('Koulen')),
			array('value'=>'Kranky', 'label'=>Mage::helper('themeconfig')->__('Kranky')),
			array('value'=>'Kreon', 'label'=>Mage::helper('themeconfig')->__('Kreon')),
			array('value'=>'Kristi', 'label'=>Mage::helper('themeconfig')->__('Kristi')),
			array('value'=>'La Belle Aurore', 'label'=>Mage::helper('themeconfig')->__('La Belle Aurore')),
			array('value'=>'Lancelot', 'label'=>Mage::helper('themeconfig')->__('Lancelot')),
			array('value'=>'Lato', 'label'=>Mage::helper('themeconfig')->__('Lato')),
			array('value'=>'League Script', 'label'=>Mage::helper('themeconfig')->__('League Script')),
			array('value'=>'Leckerli One', 'label'=>Mage::helper('themeconfig')->__('Leckerli One')),
			array('value'=>'Lekton', 'label'=>Mage::helper('themeconfig')->__('Lekton')),
			array('value'=>'Lemon', 'label'=>Mage::helper('themeconfig')->__('Lemon')),
			array('value'=>'Limelight', 'label'=>Mage::helper('themeconfig')->__('Limelight')),
			array('value'=>'Linden Hill', 'label'=>Mage::helper('themeconfig')->__('Linden Hill')),
			array('value'=>'Lobster', 'label'=>Mage::helper('themeconfig')->__('Lobster')),
			array('value'=>'Lobster Two', 'label'=>Mage::helper('themeconfig')->__('Lobster Two')),
			array('value'=>'Lora', 'label'=>Mage::helper('themeconfig')->__('Lora')),
			array('value'=>'Love Ya Like A Sister', 'label'=>Mage::helper('themeconfig')->__('Love Ya Like A Sister')),
			array('value'=>'Loved by the King', 'label'=>Mage::helper('themeconfig')->__('Loved by the King')),
			array('value'=>'Luckiest Guy', 'label'=>Mage::helper('themeconfig')->__('Luckiest Guy')),
			array('value'=>'Maiden Orange', 'label'=>Mage::helper('themeconfig')->__('Maiden Orange')),
			array('value'=>'Mako', 'label'=>Mage::helper('themeconfig')->__('Mako')),
			array('value'=>'Marck Script', 'label'=>Mage::helper('themeconfig')->__('Marck Script')),
			array('value'=>'Marko One', 'label'=>Mage::helper('themeconfig')->__('Marko One')),
			array('value'=>'Marmelad', 'label'=>Mage::helper('themeconfig')->__('Marmelad')),
			array('value'=>'Marvel', 'label'=>Mage::helper('themeconfig')->__('Marvel')),
			array('value'=>'Mate', 'label'=>Mage::helper('themeconfig')->__('Mate')),
			array('value'=>'Mate SC', 'label'=>Mage::helper('themeconfig')->__('Mate SC')),
			array('value'=>'Maven Pro', 'label'=>Mage::helper('themeconfig')->__('Maven Pro')),
			array('value'=>'Meddon', 'label'=>Mage::helper('themeconfig')->__('Meddon')),
			array('value'=>'MedievalSharp', 'label'=>Mage::helper('themeconfig')->__('MedievalSharp')),
			array('value'=>'Medula One', 'label'=>Mage::helper('themeconfig')->__('Medula One')),
			array('value'=>'Megrim', 'label'=>Mage::helper('themeconfig')->__('Megrim')),
			array('value'=>'Merienda One', 'label'=>Mage::helper('themeconfig')->__('Merienda One')),
			array('value'=>'Merriweather', 'label'=>Mage::helper('themeconfig')->__('Merriweather')),
			array('value'=>'Metal', 'label'=>Mage::helper('themeconfig')->__('Metal')),
			array('value'=>'Metamorphous', 'label'=>Mage::helper('themeconfig')->__('Metamorphous')),
			array('value'=>'Metrophobic', 'label'=>Mage::helper('themeconfig')->__('Metrophobic')),
			array('value'=>'Michroma', 'label'=>Mage::helper('themeconfig')->__('Michroma')),
			array('value'=>'Miltonian', 'label'=>Mage::helper('themeconfig')->__('Miltonian')),
			array('value'=>'Miltonian Tattoo', 'label'=>Mage::helper('themeconfig')->__('Miltonian Tattoo')),
			array('value'=>'Miniver', 'label'=>Mage::helper('themeconfig')->__('Miniver')),
			array('value'=>'Miss Fajardose', 'label'=>Mage::helper('themeconfig')->__('Miss Fajardose')),
			array('value'=>'Miss Saint Delafield', 'label'=>Mage::helper('themeconfig')->__('Miss Saint Delafield')),
			array('value'=>'Modern Antiqua', 'label'=>Mage::helper('themeconfig')->__('Modern Antiqua')),
			array('value'=>'Molengo', 'label'=>Mage::helper('themeconfig')->__('Molengo')),
			array('value'=>'Monofett', 'label'=>Mage::helper('themeconfig')->__('Monofett')),
			array('value'=>'Monoton', 'label'=>Mage::helper('themeconfig')->__('Monoton')),
			array('value'=>'Monsieur La Doulaise', 'label'=>Mage::helper('themeconfig')->__('Monsieur La Doulaise')),
			array('value'=>'Montez', 'label'=>Mage::helper('themeconfig')->__('Montez')),
			array('value'=>'Montserrat', 'label'=>Mage::helper('themeconfig')->__('Montserrat')),
			array('value'=>'Moul', 'label'=>Mage::helper('themeconfig')->__('Moul')),
			array('value'=>'Moulpali', 'label'=>Mage::helper('themeconfig')->__('Moulpali')),
			array('value'=>'Mountains of Christmas', 'label'=>Mage::helper('themeconfig')->__('Mountains of Christmas')),
			array('value'=>'Mr Bedford', 'label'=>Mage::helper('themeconfig')->__('Mr Bedford')),
			array('value'=>'Mr Dafoe', 'label'=>Mage::helper('themeconfig')->__('Mr Dafoe')),
			array('value'=>'Mr De Haviland', 'label'=>Mage::helper('themeconfig')->__('Mr De Haviland')),
			array('value'=>'Mrs Sheppards', 'label'=>Mage::helper('themeconfig')->__('Mrs Sheppards')),
			array('value'=>'Muli', 'label'=>Mage::helper('themeconfig')->__('Muli')),
			array('value'=>'Neucha', 'label'=>Mage::helper('themeconfig')->__('Neucha')),
			array('value'=>'Neuton', 'label'=>Mage::helper('themeconfig')->__('Neuton')),
			array('value'=>'News Cycle', 'label'=>Mage::helper('themeconfig')->__('News Cycle')),
			array('value'=>'Niconne', 'label'=>Mage::helper('themeconfig')->__('Niconne')),
			array('value'=>'Nixie One', 'label'=>Mage::helper('themeconfig')->__('Nixie One')),
			array('value'=>'Nobile', 'label'=>Mage::helper('themeconfig')->__('Nobile')),
			array('value'=>'Nokora', 'label'=>Mage::helper('themeconfig')->__('Nokora')),
			array('value'=>'Nosifer', 'label'=>Mage::helper('themeconfig')->__('Nosifer')),
			array('value'=>'Nothing You Could Do', 'label'=>Mage::helper('themeconfig')->__('Nothing You Could Do')),
			array('value'=>'Noticia Text', 'label'=>Mage::helper('themeconfig')->__('Noticia Text')),
			array('value'=>'Nova Cut', 'label'=>Mage::helper('themeconfig')->__('Nova Cut')),
			array('value'=>'Nova Flat', 'label'=>Mage::helper('themeconfig')->__('Nova Flat')),
			array('value'=>'Nova Mono', 'label'=>Mage::helper('themeconfig')->__('Nova Mono')),
			array('value'=>'Nova Oval', 'label'=>Mage::helper('themeconfig')->__('Nova Oval')),
			array('value'=>'Nova Round', 'label'=>Mage::helper('themeconfig')->__('Nova Round')),
			array('value'=>'Nova Script', 'label'=>Mage::helper('themeconfig')->__('Nova Script')),
			array('value'=>'Nova Slim', 'label'=>Mage::helper('themeconfig')->__('Nova Slim')),
			array('value'=>'Nova Square', 'label'=>Mage::helper('themeconfig')->__('Nova Square')),
			array('value'=>'Numans', 'label'=>Mage::helper('themeconfig')->__('Numans')),
			array('value'=>'Nunito', 'label'=>Mage::helper('themeconfig')->__('Nunito')),
			array('value'=>'Odor Mean Chey', 'label'=>Mage::helper('themeconfig')->__('Odor Mean Chey')),
			array('value'=>'Old Standard TT', 'label'=>Mage::helper('themeconfig')->__('Old Standard TT')),
			array('value'=>'Open Sans', 'label'=>Mage::helper('themeconfig')->__('Open Sans')),
			array('value'=>'Open Sans Condensed', 'label'=>Mage::helper('themeconfig')->__('Open Sans Condensed')),
			array('value'=>'Orbitron', 'label'=>Mage::helper('themeconfig')->__('Orbitron')),
			array('value'=>'Original Surfer', 'label'=>Mage::helper('themeconfig')->__('Original Surfer')),
			array('value'=>'Oswald', 'label'=>Mage::helper('themeconfig')->__('Oswald')),
			array('value'=>'Over the Rainbow', 'label'=>Mage::helper('themeconfig')->__('Over the Rainbow')),
			array('value'=>'Overlock', 'label'=>Mage::helper('themeconfig')->__('Overlock')),
			array('value'=>'Overlock SC', 'label'=>Mage::helper('themeconfig')->__('Overlock SC')),
			array('value'=>'Ovo', 'label'=>Mage::helper('themeconfig')->__('Ovo')),
			array('value'=>'PT Sans', 'label'=>Mage::helper('themeconfig')->__('PT Sans')),
			array('value'=>'PT Sans Caption', 'label'=>Mage::helper('themeconfig')->__('PT Sans Caption')),
			array('value'=>'PT Sans Narrow', 'label'=>Mage::helper('themeconfig')->__('PT Sans Narrow')),
			array('value'=>'PT Serif', 'label'=>Mage::helper('themeconfig')->__('PT Serif')),
			array('value'=>'PT Serif Caption', 'label'=>Mage::helper('themeconfig')->__('PT Serif Caption')),
			array('value'=>'Pacifico', 'label'=>Mage::helper('themeconfig')->__('Pacifico')),
			array('value'=>'Passero One', 'label'=>Mage::helper('themeconfig')->__('Passero One')),
			array('value'=>'Passion One', 'label'=>Mage::helper('themeconfig')->__('Passion One')),
			array('value'=>'Patrick Hand', 'label'=>Mage::helper('themeconfig')->__('Patrick Hand')),
			array('value'=>'Patua One', 'label'=>Mage::helper('themeconfig')->__('Patua One')),
			array('value'=>'Paytone One', 'label'=>Mage::helper('themeconfig')->__('Paytone One')),
			array('value'=>'Permanent Marker', 'label'=>Mage::helper('themeconfig')->__('Permanent Marker')),
			array('value'=>'Petrona', 'label'=>Mage::helper('themeconfig')->__('Petrona')),
			array('value'=>'Philosopher', 'label'=>Mage::helper('themeconfig')->__('Philosopher')),
			array('value'=>'Piedra', 'label'=>Mage::helper('themeconfig')->__('Piedra')),
			array('value'=>'Pinyon Script', 'label'=>Mage::helper('themeconfig')->__('Pinyon Script')),
			array('value'=>'Plaster', 'label'=>Mage::helper('themeconfig')->__('Plaster')),
			array('value'=>'Play', 'label'=>Mage::helper('themeconfig')->__('Play')),
			array('value'=>'Playball', 'label'=>Mage::helper('themeconfig')->__('Playball')),
			array('value'=>'Playfair Display', 'label'=>Mage::helper('themeconfig')->__('Playfair Display')),
			array('value'=>'Podkova', 'label'=>Mage::helper('themeconfig')->__('Podkova')),
			array('value'=>'Poller One', 'label'=>Mage::helper('themeconfig')->__('Poller One')),
			array('value'=>'Poly', 'label'=>Mage::helper('themeconfig')->__('Poly')),
			array('value'=>'Pompiere', 'label'=>Mage::helper('themeconfig')->__('Pompiere')),
			array('value'=>'Prata', 'label'=>Mage::helper('themeconfig')->__('Prata')),
			array('value'=>'Preahvihear', 'label'=>Mage::helper('themeconfig')->__('Preahvihear')),
			array('value'=>'Prociono', 'label'=>Mage::helper('themeconfig')->__('Prociono')),
			array('value'=>'Puritan', 'label'=>Mage::helper('themeconfig')->__('Puritan')),
			array('value'=>'Quantico', 'label'=>Mage::helper('themeconfig')->__('Quantico')),
			array('value'=>'Quattrocento', 'label'=>Mage::helper('themeconfig')->__('Quattrocento')),
			array('value'=>'Quattrocento Sans', 'label'=>Mage::helper('themeconfig')->__('Quattrocento Sans')),
			array('value'=>'Questrial', 'label'=>Mage::helper('themeconfig')->__('Questrial')),
			array('value'=>'Quicksand', 'label'=>Mage::helper('themeconfig')->__('Quicksand')),
			array('value'=>'Qwigley', 'label'=>Mage::helper('themeconfig')->__('Qwigley')),
			array('value'=>'Radley', 'label'=>Mage::helper('themeconfig')->__('Radley')),
			array('value'=>'Raleway', 'label'=>Mage::helper('themeconfig')->__('Raleway')),
			array('value'=>'Rammetto One', 'label'=>Mage::helper('themeconfig')->__('Rammetto One')),
			array('value'=>'Rancho', 'label'=>Mage::helper('themeconfig')->__('Rancho')),
			array('value'=>'Rationale', 'label'=>Mage::helper('themeconfig')->__('Rationale')),
			array('value'=>'Redressed', 'label'=>Mage::helper('themeconfig')->__('Redressed')),
			array('value'=>'Reenie Beanie', 'label'=>Mage::helper('themeconfig')->__('Reenie Beanie')),
			array('value'=>'Ribeye', 'label'=>Mage::helper('themeconfig')->__('Ribeye')),
			array('value'=>'Ribeye Marrow', 'label'=>Mage::helper('themeconfig')->__('Ribeye Marrow')),
			array('value'=>'Righteous', 'label'=>Mage::helper('themeconfig')->__('Righteous')),
			array('value'=>'Rochester', 'label'=>Mage::helper('themeconfig')->__('Rochester')),
			array('value'=>'Rock Salt', 'label'=>Mage::helper('themeconfig')->__('Rock Salt')),
			array('value'=>'Rokkitt', 'label'=>Mage::helper('themeconfig')->__('Rokkitt')),
			array('value'=>'Rosario', 'label'=>Mage::helper('themeconfig')->__('Rosario')),
			array('value'=>'Ruge Boogie', 'label'=>Mage::helper('themeconfig')->__('Ruge Boogie')),
			array('value'=>'Ruslan Display', 'label'=>Mage::helper('themeconfig')->__('Ruslan Display')),
			array('value'=>'Ruthie', 'label'=>Mage::helper('themeconfig')->__('Ruthie')),
			array('value'=>'Sail', 'label'=>Mage::helper('themeconfig')->__('Sail')),
			array('value'=>'Salsa', 'label'=>Mage::helper('themeconfig')->__('Salsa')),
			array('value'=>'Sancreek', 'label'=>Mage::helper('themeconfig')->__('Sancreek')),
			array('value'=>'Sansita One', 'label'=>Mage::helper('themeconfig')->__('Sansita One')),
			array('value'=>'Sarina', 'label'=>Mage::helper('themeconfig')->__('Sarina')),
			array('value'=>'Satisfy', 'label'=>Mage::helper('themeconfig')->__('Satisfy')),
			array('value'=>'Schoolbell', 'label'=>Mage::helper('themeconfig')->__('Schoolbell')),
			array('value'=>'Shadows Into Light', 'label'=>Mage::helper('themeconfig')->__('Shadows Into Light')),
			array('value'=>'Shanti', 'label'=>Mage::helper('themeconfig')->__('Shanti')),
			array('value'=>'Short Stack', 'label'=>Mage::helper('themeconfig')->__('Short Stack')),
			array('value'=>'Siemreap', 'label'=>Mage::helper('themeconfig')->__('Siemreap')),
			array('value'=>'Sigmar One', 'label'=>Mage::helper('themeconfig')->__('Sigmar One')),
			array('value'=>'Signika', 'label'=>Mage::helper('themeconfig')->__('Signika')),
			array('value'=>'Signika Negative', 'label'=>Mage::helper('themeconfig')->__('Signika Negative')),
			array('value'=>'Six Caps', 'label'=>Mage::helper('themeconfig')->__('Six Caps')),
			array('value'=>'Slackey', 'label'=>Mage::helper('themeconfig')->__('Slackey')),
			array('value'=>'Smokum', 'label'=>Mage::helper('themeconfig')->__('Smokum')),
			array('value'=>'Smythe', 'label'=>Mage::helper('themeconfig')->__('Smythe')),
			array('value'=>'Sniglet', 'label'=>Mage::helper('themeconfig')->__('Sniglet')),
			array('value'=>'Snippet', 'label'=>Mage::helper('themeconfig')->__('Snippet')),
			array('value'=>'Sofia', 'label'=>Mage::helper('themeconfig')->__('Sofia')),
			array('value'=>'Sorts Mill Goudy', 'label'=>Mage::helper('themeconfig')->__('Sorts Mill Goudy')),
			array('value'=>'Special Elite', 'label'=>Mage::helper('themeconfig')->__('Special Elite')),
			array('value'=>'Spicy Rice', 'label'=>Mage::helper('themeconfig')->__('Spicy Rice')),
			array('value'=>'Spinnaker', 'label'=>Mage::helper('themeconfig')->__('Spinnaker')),
			array('value'=>'Spirax', 'label'=>Mage::helper('themeconfig')->__('Spirax')),
			array('value'=>'Squada One', 'label'=>Mage::helper('themeconfig')->__('Squada One')),
			array('value'=>'Stardos Stencil', 'label'=>Mage::helper('themeconfig')->__('Stardos Stencil')),
			array('value'=>'Stint Ultra Condensed', 'label'=>Mage::helper('themeconfig')->__('Stint Ultra Condensed')),
			array('value'=>'Stoke', 'label'=>Mage::helper('themeconfig')->__('Stoke')),
			array('value'=>'Sue Ellen Francisco', 'label'=>Mage::helper('themeconfig')->__('Sue Ellen Francisco')),
			array('value'=>'Sunshiney', 'label'=>Mage::helper('themeconfig')->__('Sunshiney')),
			array('value'=>'Supermercado One', 'label'=>Mage::helper('themeconfig')->__('Supermercado One')),
			array('value'=>'Suwannaphum', 'label'=>Mage::helper('themeconfig')->__('Suwannaphum')),
			array('value'=>'Swanky and Moo Moo', 'label'=>Mage::helper('themeconfig')->__('Swanky and Moo Moo')),
			array('value'=>'Syncopate', 'label'=>Mage::helper('themeconfig')->__('Syncopate')),
			array('value'=>'Tangerine', 'label'=>Mage::helper('themeconfig')->__('Tangerine')),
			array('value'=>'Taprom', 'label'=>Mage::helper('themeconfig')->__('Taprom')),
			array('value'=>'Tenor Sans', 'label'=>Mage::helper('themeconfig')->__('Tenor Sans')),
			array('value'=>'Terminal Dosis', 'label'=>Mage::helper('themeconfig')->__('Terminal Dosis')),
			array('value'=>'The Girl Next Door', 'label'=>Mage::helper('themeconfig')->__('The Girl Next Door')),
			array('value'=>'Tienne', 'label'=>Mage::helper('themeconfig')->__('Tienne')),
			array('value'=>'Tinos', 'label'=>Mage::helper('themeconfig')->__('Tinos')),
			array('value'=>'Trade Winds', 'label'=>Mage::helper('themeconfig')->__('Trade Winds')),
			array('value'=>'Trykker', 'label'=>Mage::helper('themeconfig')->__('Trykker')),
			array('value'=>'Tulpen One', 'label'=>Mage::helper('themeconfig')->__('Tulpen One')),
			array('value'=>'Ubuntu', 'label'=>Mage::helper('themeconfig')->__('Ubuntu')),
			array('value'=>'Ubuntu Condensed', 'label'=>Mage::helper('themeconfig')->__('Ubuntu Condensed')),
			array('value'=>'Ubuntu Mono', 'label'=>Mage::helper('themeconfig')->__('Ubuntu Mono')),
			array('value'=>'Ultra', 'label'=>Mage::helper('themeconfig')->__('Ultra')),
			array('value'=>'Uncial Antiqua', 'label'=>Mage::helper('themeconfig')->__('Uncial Antiqua')),
			array('value'=>'UnifrakturCook', 'label'=>Mage::helper('themeconfig')->__('UnifrakturCook')),
			array('value'=>'UnifrakturMaguntia', 'label'=>Mage::helper('themeconfig')->__('UnifrakturMaguntia')),
			array('value'=>'Unkempt', 'label'=>Mage::helper('themeconfig')->__('Unkempt')),
			array('value'=>'Unlock', 'label'=>Mage::helper('themeconfig')->__('Unlock')),
			array('value'=>'Unna', 'label'=>Mage::helper('themeconfig')->__('Unna')),
			array('value'=>'VT323', 'label'=>Mage::helper('themeconfig')->__('VT323')),
			array('value'=>'Varela', 'label'=>Mage::helper('themeconfig')->__('Varela')),
			array('value'=>'Varela Round', 'label'=>Mage::helper('themeconfig')->__('Varela Round')),
			array('value'=>'Vast Shadow', 'label'=>Mage::helper('themeconfig')->__('Vast Shadow')),
			array('value'=>'Vibur', 'label'=>Mage::helper('themeconfig')->__('Vibur')),
			array('value'=>'Vidaloka', 'label'=>Mage::helper('themeconfig')->__('Vidaloka')),
			array('value'=>'Viga', 'label'=>Mage::helper('themeconfig')->__('Viga')),
			array('value'=>'Volkhov', 'label'=>Mage::helper('themeconfig')->__('Volkhov')),
			array('value'=>'Vollkorn', 'label'=>Mage::helper('themeconfig')->__('Vollkorn')),
			array('value'=>'Voltaire', 'label'=>Mage::helper('themeconfig')->__('Voltaire')),
			array('value'=>'Waiting for the Sunrise', 'label'=>Mage::helper('themeconfig')->__('Waiting for the Sunrise')),
			array('value'=>'Wallpoet', 'label'=>Mage::helper('themeconfig')->__('Wallpoet')),
			array('value'=>'Walter Turncoat', 'label'=>Mage::helper('themeconfig')->__('Walter Turncoat')),
			array('value'=>'Wire One', 'label'=>Mage::helper('themeconfig')->__('Wire One')),
			array('value'=>'Yanone Kaffeesatz', 'label'=>Mage::helper('themeconfig')->__('Yanone Kaffeesatz')),
			array('value'=>'Yellowtail', 'label'=>Mage::helper('themeconfig')->__('Yellowtail')),
			array('value'=>'Yeseva One', 'label'=>Mage::helper('themeconfig')->__('Yeseva One')),
			array('value'=>'Yesteryear', 'label'=>Mage::helper('themeconfig')->__('Yesteryear')),
			array('value'=>'Zeyada', 'label'=>Mage::helper('themeconfig')->__('Zeyada')),
        );
    }
}