<?php
/**
 * Avalanche for Magento 1.6+
 * Designed by Fast Division (http://fastdivision.com)
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file license.txt.
 * It is also available through the world-wide-web at this URL:
 * http://fastdivision.com/legal/license.txt
 *
 * @author     Fast Division
 * @version    1.3.0
 * @copyright  Copyright 2012 Fast Division
 * @license    http://fastdivision.com/legal/license.txt
 */
?>
<?php echo $this->getChildHtml('catalog.compare.sidebar') ?>
<?php /*<div class="white-box">
	<h3>Specials</h3>
	<div class="white-box-inner">
		<p>Test 123</p>
	</div>
	
	<h3>Customer Service</h3>
	<div class="white-box-inner">
		<p>Test 123</p>
	</div>
</div>*/ ?>