<?php
/**
 * Avalanche for Magento 1.6+
 * Designed by Fast Division (http://fastdivision.com)
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file license.txt.
 * It is also available through the world-wide-web at this URL:
 * http://fastdivision.com/legal/license.txt
 *
 * @author     Fast Division
 * @version    1.3.0
 * @copyright  Copyright 2012 Fast Division
 * @license    http://fastdivision.com/legal/license.txt
 */
?>
<?php
/**
 * Product list toolbar
 *
 * @see Mage_Catalog_Block_Product_List_Toolbar
 */
?>
<?php if($this->getCollection()->getSize()): ?>
	<div class="pager<?php if(Mage::getStoreConfigFlag('avalanche_config/avalanche_product_listings/avalanche_ajax_pager')): ?> pager-visible<?php endif; ?>">
		<?php echo $this->getPagerHtml() ?>
	</div>
	
	<?php if( $this->isExpanded() ): ?>
	<div class="sorter">
		<div class="catalog-mode">
	        <?php if($this->isEnabledViewSwitcher()): ?>
	            <?php $_modes = $this->getModes(); ?>
	            <?php if($_modes && count($_modes) > 1): ?>
	            <?php foreach($this->getModes() as $_code => $_label): ?>
	            <div class="view-mode">
	                <?php if($this->isModeActive($_code)): ?>
	                    <strong title="<?php echo $_label ?>" class="<?php echo strtolower($_code); ?>"><?php echo $_label ?></strong>&nbsp;
	                <?php else: ?>
	                    <a href="<?php echo $this->getModeUrl($_code) ?>" title="<?php echo $_label ?>" class="<?php echo strtolower($_code); ?>"><?php echo $_label ?></a>&nbsp;
	                <?php endif; ?>
	            </div>
	            <?php endforeach; ?>
	            <?php endif; ?>
	        <?php endif; ?>
		</div>
		<div class="results-sort sort-by">
			<label><span><?php echo $this->__('Sort by') ?></span></label>
			<select class="options_sort" onchange="setLocation(this.value)">
				<?php foreach($this->getAvailableOrders() as $_key=>$_order): ?>
					<option value="<?php echo $this->getOrderUrl($_key, 'desc') ?>"<?php if($this->isOrderCurrent($_key)): ?> selected="selected"<?php endif; ?>>
						<?php echo $_order ?>
					</option>
				<?php endforeach; ?>
			</select>
		</div>
	</div>
	<?php endif; ?>
<?php endif ?>
