<?php
/**
 * Avalanche for Magento 1.6+
 * Designed by Fast Division (http://fastdivision.com)
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file license.txt.
 * It is also available through the world-wide-web at this URL:
 * http://fastdivision.com/legal/license.txt
 *
 * @author     Fast Division
 * @version    1.3.0
 * @copyright  Copyright 2012 Fast Division
 * @license    http://fastdivision.com/legal/license.txt
 */
?>
<?php
/**
 * Category layered navigation state
 *
 * @see Mage_Catalog_Block_Layer_State
 */
?>
<?php $_filters = $this->getActiveFilters() ?>
<?php if(!empty($_filters)): ?>
<div class="currently">
    <h2>
		<?php echo $this->__('Selected Filters') ?>
		<div class="actions"><a href="<?php echo $this->getClearUrl() ?>"><?php echo $this->__('Clear All') ?></a></div>
	</h2>
    <ul>
    <?php foreach ($_filters as $_filter): ?>
        <li>
			<a href="<?php echo $_filter->getRemoveUrl() ?>" title="<?php echo $this->__('Remove This Item') ?>" class="remove-filter"><img src="<?php echo $this->getSkinUrl('images/remove-filter.png') ?>" alt="X"></a>
            <span class="label"><?php echo $this->__($_filter->getName()) ?>:</span> <strong><?php echo $this->stripTags($_filter->getLabel()) ?></strong>
        </li>
    <?php endforeach; ?>
    </ul>
</div>
<?php endif; ?>
