<?php
/**
 * Avalanche for Magento 1.6+
 * Designed by Fast Division (http://fastdivision.com)
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file license.txt.
 * It is also available through the world-wide-web at this URL:
 * http://fastdivision.com/legal/license.txt
 *
 * @author     Fast Division
 * @version    1.3.0
 * @copyright  Copyright 2012 Fast Division
 * @license    http://fastdivision.com/legal/license.txt
 */
?>
<?php
/**
 * Category layered navigation
 *
 * @see Mage_Catalog_Block_Layer_View
 */
?>
<?php if($this->canShowBlock()): ?>
<div class="black-box">
	<div class="block block-layered-nav">
	    <div class="block-content">
	        <?php echo $this->getStateHtml() ?>
	        <?php if($this->canShowOptions()): ?>
                <?php $_filters = $this->getFilters() ?>
                <?php foreach ($_filters as $_filter): ?>
                <?php if($_filter->getItemsCount()): ?>
					<h2><?php echo $this->__($_filter->getName()) ?></h2>
                    <?php echo $_filter->getHtml() ?>
                <?php endif; ?>
                <?php endforeach; ?>
	        <?php endif; ?>
	    </div>
	</div>
</div><br>
<?php endif; ?>
