<?php
/**
 * Avalanche Mobile for Magento 1.6+
 * Designed by Fast Division (http://fastdivision.com)
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file license.txt.
 * It is also available through the world-wide-web at this URL:
 * http://fastdivision.com/legal/license.txt
 *
 * @author     Fast Division
 * @version    1.0.0
 * @copyright  Copyright 2012 Fast Division
 * @license    http://fastdivision.com/legal/license.txt
 */
?>
<div class="col2-set">
    <div class="col-1">
        <div class="box">
            <div class="box-title">
                <h3><?php echo $this->__('Contact Information') ?><a href="<?php echo $this->getUrl('customer/account/edit') ?>" class="edit-link"><?php echo $this->__('Edit') ?></a></h3>
            </div>
            <div class="box-content">
                <p>
                    <strong><?php echo $this->htmlEscape($this->getCustomer()->getName()) ?></strong><br>
                    <?php echo $this->htmlEscape($this->getCustomer()->getEmail()) ?><br><br>
                    <a href="<?php echo $this->getChangePasswordUrl() ?>" class="button small-button"><?php echo $this->__('Change Password') ?></a>
                </p><br>
            </div>
        </div>
    </div>
    <?php if( $this->isNewsletterEnabled() ): ?>
    <div class="col-2">
        <div class="box">
            <div class="box-title">
                <h3><?php echo $this->__('Newsletters') ?><a href="<?php echo $this->getUrl('newsletter/manage') ?>" class="edit-link"><?php echo $this->__('Edit') ?></a></h3>
            </div>
            <div class="box-content">
                <p>
                    <?php if( $this->getIsSubscribed() ): ?>
                        <?php echo $this->__("You are currently subscribed to 'General Subscription'.") ?>
                    <?php else: ?>
                        <?php echo $this->__('You are currently not subscribed to any newsletter.') ?>
                    <?php endif; ?>
                </p><br>
            </div>
        </div>
    </div>
    <?php endif; ?>
</div>