<?php
/**
 * Avalanche for Magento 1.6+
 * Designed by Fast Division (http://fastdivision.com)
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file license.txt.
 * It is also available through the world-wide-web at this URL:
 * http://fastdivision.com/legal/license.txt
 *
 * @author     Fast Division
 * @version    1.3.0
 * @copyright  Copyright 2012 Fast Division
 * @license    http://fastdivision.com/legal/license.txt
 */
?>
<div id="checkout-progress-container" class="clearfix">
<ul class="checkout-progress" id="checkout-progress-state">
<?php foreach ($this->getSteps() as $_step): ?>
    <li title="<?php echo $_step->getLabel() ?>"<?php if($_step->getIsActive()): ?> class="active"<?php endif; ?>><span><?php echo $_step->getLabel() ?></span></li>
<?php endforeach; ?>
</ul>
</div>
<script type="text/javascript">decorateGeneric($$('#checkout-progress-state li'), ['first','last']);</script>