<?php
/**
 * Avalanche for Magento 1.6+
 * Designed by Fast Division (http://fastdivision.com)
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file license.txt.
 * It is also available through the world-wide-web at this URL:
 * http://fastdivision.com/legal/license.txt
 *
 * @author     Fast Division
 * @version    1.3.0
 * @copyright  Copyright 2012 Fast Division
 * @license    http://fastdivision.com/legal/license.txt
 */
?>
<h1><?php echo $this->__('My Tags') ?></h1>

<div class="white-box-inner">
	<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
	<div class="my-tag-edit clearfix">
	    <?php echo $this->__('<strong>Tag Name:</strong> %s', $this->htmlEscape($this->getTagInfo()->getName())) ?>
		<a href="#" title="<?php echo $this->__('Delete') ?>" onclick="if(confirm('<?php echo $this->__('Are you sure you want to delete this tag?') ?>')) window.location='<?php echo $this->getTagInfo()->getRemoveTagUrl(); ?>'; return false;" class="btn-remove"><span><?php echo $this->__('Delete') ?></span></a>
	</div>

	<div class="toolbar clearfix"><?php echo $this->getToolbarHtml() ?></div>
	<table class="data-table" id="my-tags-table">
	<?php if( sizeof($this->getMyProducts()) > 0 ): ?>
	    <col width="1" />
	    <col />
	    <col width="1" />
	    <tbody>
	    <?php $iterator = 0 ?>
	    <?php foreach($this->getMyProducts() as $_product): ?>
	        <tr<?php if($iterator % 2 == 0): ?> class="odd"<?php $iterator++;endif; ?>>
	            <td><a href="<?php echo $_product->getProductUrl(); ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(100, 100); ?>" width="100" height="100" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" /></a></td>
	            <td>
	                <a href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->htmlEscape($_product->getName()) ?></a><br/>
	                <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
	                <?php echo $this->getPriceHtml($_product) ?>
	                <?php echo $this->htmlEscape($_product->getDescription()) ?>
	            </td>
	            <td>
	                <?php if($_product->isSaleable()): ?>
	                    <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getUrl('checkout/cart/add',array('product'=>$_product->getId())) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
	                <?php endif; ?>
	                <?php if ($this->helper('wishlist')->isAllow()) : ?>
	                <ul class="add-to-links">
	                    <li>
	                        <a href="<?php echo $this->getUrl('wishlist/index/add',array('product'=>$_product->getId())) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a>
	                    </li>
	                </ul>
	                <?php endif; ?>
	            </td>
	        </tr>
	    <?php endforeach; ?>
	    </tbody>
	<?php else: ?>
	    <tbody>
	        <tr>
	            <td>
	                <?php echo $this->__("Unable to find any products tagged with '%s' in the current store", $this->htmlEscape($this->getTagInfo()->getName()) ) ?>
	            </td>
	        </tr>
	    </tbody>
	<?php endif; ?>
	</table>
	<div class="toolbar clearfix"><?php echo $this->getToolbarHtml() ?></div>
	<div class="buttons-set clearfix">
	   <a href="<?php echo $this->getUrl('*/*/')?>"><small>&laquo; </small><?php echo $this->__('Back to Tags List')?></a>
	</div>
</div>