<?php
/**
 * Avalanche for Magento 1.6+
 * Designed by Fast Division (http://fastdivision.com)
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file license.txt.
 * It is also available through the world-wide-web at this URL:
 * http://fastdivision.com/legal/license.txt
 *
 * @author     Fast Division
 * @version    1.3.0
 * @copyright  Copyright 2012 Fast Division
 * @license    http://fastdivision.com/legal/license.txt
 */
?>
<div style=" float:left; width:653px;">
    <img src="<?php echo $this->getSkinUrl('images/media/home_co_main.jpg');?>" alt="" />
</div>
<div style="float:right; width:280px;">
    <div style="margin:0 0 10px;" ><img src="<?php echo $this->getSkinUrl('images/media/home_co_tr.gif');?>" alt="" /></div>
    <div><img src="<?php echo $this->getSkinUrl('images/media/home_co_br.gif');?>" alt="" /></div>
</div>
<div class="clearer"></div>
<div style="margin:10px 0 0;"><img src="<?php echo $this->getSkinUrl('images/media/home_co_bottom.gif');?>" alt="" /></div>
