<?php
/**
 * Avalanche for Magento 1.6+
 * Designed by Fast Division (http://fastdivision.com)
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file license.txt.
 * It is also available through the world-wide-web at this URL:
 * http://fastdivision.com/legal/license.txt
 *
 * @author     Fast Division
 * @version    1.3.0
 * @copyright  Copyright 2012 Fast Division
 * @license    http://fastdivision.com/legal/license.txt
 */
?>
<?php if(count($this->getStores())>1): ?>
<li class="flags">
	<div class="language-switcher">
	    <?php foreach ($this->getStores() as $_lang): ?>
	        <a href="<?php echo $_lang->getCurrentUrl() ?>"><img
	src="<?php echo $this->getSkinUrl('images/flags/' . $this->htmlEscape($_lang->getCode()) . '.gif') ?>" width="16" height="11"
	alt="<?php echo $this->htmlEscape($_lang->getName()) ?>"/></a>
	    <?php endforeach; ?>
	</div>
</li>
<?php endif; ?>