<?php
/**
 * Avalanche for Magento 1.6+
 * Designed by Fast Division (http://fastdivision.com)
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file license.txt.
 * It is also available through the world-wide-web at this URL:
 * http://fastdivision.com/legal/license.txt
 *
 * @author     Fast Division
 * @version    1.3.0
 * @copyright  Copyright 2012 Fast Division
 * @license    http://fastdivision.com/legal/license.txt
 */
?>
<!DOCTYPE html> 
<!--[if lt IE 7 ]> <html lang="en" class="ie ie6 no-js"> <![endif]--> 
<!--[if IE 7 ]>    <html lang="en" class="ie ie7 no-js"> <![endif]--> 
<!--[if IE 8 ]>    <html lang="en" class="ie ie8 no-js"> <![endif]--> 
<!--[if IE 9 ]>    <html lang="en" class="ie ie9 no-js"> <![endif]--> 
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="<?php echo $this->getLang() ?>" class="no-js"> <!--<![endif]--> 
<head>
	<?php echo $this->getChildHtml('head') ?>
</head>

<body class="<?php echo $this->getBodyClass() ? trim($this->getBodyClass()) : '' ?> <?php echo Mage::helper('themeconfig')->getStoreClass(); ?>">
<?php echo $this->getChildHtml('after_body_start') ?>
<?php echo $this->getChildHtml('global_notices') ?>

<div id="wrapper">
	<div id="container" class="container_12">
		<?php echo $this->getChildHtml('header') ?>
		
		<div id="main" role="main" class="clearfix">
		    <?php echo $this->getChildHtml('breadcrumbs') ?>
			<div class="global-messages">
	        	<?php echo $this->getChildHtml('global_messages') ?>
			</div>
			<div id="content">
				<div id="account" class="grid_3">
					<?php echo $this->getChildHtml('left') ?>
				</div>
				<div id="account-page" class="grid_9 alpha omega">
					<div class="white-box">
						<?php echo $this->getChildHtml('content') ?>
					</div>
				</div>
			</div>
		</div>
		
	    <?php echo $this->getChildHtml('footer') ?>
	</div>
</div>

<?php echo $this->getChildHtml('before_body_end') ?>
<?php echo $this->getAbsoluteFooter() ?>
<?php echo $this->getChildHtml('foot'); /* Load JS in Footer */ ?>

</body>
</html>
