<?php
/**
 * Avalanche for Magento 1.6+
 * Designed by Fast Division (http://fastdivision.com)
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file license.txt.
 * It is also available through the world-wide-web at this URL:
 * http://fastdivision.com/legal/license.txt
 *
 * @author     Fast Division
 * @version    1.3.0
 * @copyright  Copyright 2012 Fast Division
 * @license    http://fastdivision.com/legal/license.txt
 */
?>
<div id="product-overview" class="white-box">
	<h2><?php echo $this->__('Overview') ?></h2>
	<div class="white-box-inner">
		<p><?php echo Mage::helper('themeconfig')->getCleanContent($this->helper('catalog/output')->productAttribute($this->getProduct(), nl2br($this->getProduct()->getDescription()), 'description')) ?></p>
		<?php if(Mage::getStoreConfig('avalanche_social/general/button_location') == 'overview'): ?>
		    <?php echo $this->getChildHtml('social-buttons') ?>
		<?php endif; ?>
	</div>
</div>