<?php
/**
 * Avalanche Mobile for Magento 1.6+
 * Designed by Fast Division (http://fastdivision.com)
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file license.txt.
 * It is also available through the world-wide-web at this URL:
 * http://fastdivision.com/legal/license.txt
 *
 * @author     Fast Division
 * @version    1.0.0
 * @copyright  Copyright 2012 Fast Division
 * @license    http://fastdivision.com/legal/license.txt
 */
?>
<div id="cart-preview" class="side-area side-area-right hide-side-area">
  <div class="side-nav">
  	<div id="ios-arrow-left">Back</div>
  	<a href="<?php echo $this->getUrl() ?>" class="home"><?php echo $this->__('Cart') ?></a>
  </div>
  <div class="side-content">
      <ul>
        <?php echo $this->getChildHtml('quickcart') ?>
      </ul>
  </div>
  <div id="category-nav-overlay"></div>
  <div id="category-overlay"></div>
</div>