<?php
/**
 * Avalanche Mobile for Magento 1.6+
 * Designed by Fast Division (http://fastdivision.com)
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file license.txt.
 * It is also available through the world-wide-web at this URL:
 * http://fastdivision.com/legal/license.txt
 *
 * @author     Fast Division
 * @version    1.0.0
 * @copyright  Copyright 2012 Fast Division
 * @license    http://fastdivision.com/legal/license.txt
 */
?>
<div id="cart">
	<div class="white-box">
		<h1><?php echo $this->__('Shopping Cart') ?></h1>
		
		<div class="white-box-inner">
			<div class="cart-empty">
				<div class="page-messages">
			    	<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
				</div>
			    <h4><?php echo $this->__('Your shopping cart is empty.') ?></h4>
			    <p><?php echo $this->__('<strong><a href="%s">Click here</a></strong> to continue shopping.', $this->getContinueShoppingUrl()) ?></p>
			</div>
		</div>
	</div>
</div>