<?php
/**
 * Avalanche Mobile for Magento 1.6+
 * Designed by Fast Division (http://fastdivision.com)
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file license.txt.
 * It is also available through the world-wide-web at this URL:
 * http://fastdivision.com/legal/license.txt
 *
 * @author     Fast Division
 * @version    1.0.0
 * @copyright  Copyright 2012 Fast Division
 * @license    http://fastdivision.com/legal/license.txt
 */
?>
<div class="white-box">
    <h1><?php echo $this->__('Forgot Your Password?') ?></h1>

	<div class="white-box-inner">
		<div class="page-messages">
			<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
		</div>
		<form action="<?php echo $this->getUrl('*/*/forgotpasswordpost') ?>" method="post" id="form-validate">
		    <div class="fieldset">
		        <p><?php echo $this->__('Please enter your email below and we will send you a new password.') ?></p>
		        <ul class="form-list">
		            <li>
		                <label for="email_address" class="required"><?php echo $this->__('Email') ?><em>*</em></label>
		                <div class="input-box">
		                    <input type="text" name="email" alt="email" id="email_address" class="input-text required-entry validate-email" value="<?php echo $this->htmlEscape($this->getEmailValue()) ?>" />
		                </div>
		            </li>
		        </ul>
		    </div>
		    <div class="buttons-set">
		        <button type="submit" title="<?php echo $this->__('Recover Password') ?>" class="action-button"><span><?php echo $this->__('Recover Password') ?></span></button>
		    </div><br/>
		</form>
		<script type="text/javascript">
		//<![CDATA[
		    var dataForm = new VarienForm('form-validate', true);
		//]]>
		</script>
	</div>
</div>