<?php
/**
 * Avalanche for Magento 1.6+
 * Designed by Fast Division (http://fastdivision.com)
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file license.txt.
 * It is also available through the world-wide-web at this URL:
 * http://fastdivision.com/legal/license.txt
 *
 * @author     Fast Division
 * @version    1.3.0
 * @copyright  Copyright 2012 Fast Division
 * @license    http://fastdivision.com/legal/license.txt
 */
?>

<div id="newsletter" class="grid_12 white-box alpha omega">
	<div class="inline-row">
		<form action="<?php echo $this->getFormActionUrl() ?>" method="post" id="newsletter-validate-detail">
			<label for="newsletter-signup"><?php echo Mage::getStoreConfig('avalanche_config/avalanche_footer/avalanche_subscriptionsignup') ?> &nbsp;</label>
			<input type="text" name="email" id="newsletter-signup" style="width: 200px" title="<?php echo $this->__('Sign up for our newsletter') ?>" placeholder="<?php echo $this->__('Enter your email address'); ?>">		
			<button type="submit" title="<?php echo $this->__('Submit') ?>" class="button"><?php echo $this->__('Submit') ?></button>
		</form>
	</div>
</div>