<?php
/**
 * Avalanche for Magento 1.6+
 * Designed by Fast Division (http://fastdivision.com)
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file license.txt.
 * It is also available through the world-wide-web at this URL:
 * http://fastdivision.com/legal/license.txt
 *
 * @author     Fast Division
 * @version    1.3.0
 * @copyright  Copyright 2012 Fast Division
 * @license    http://fastdivision.com/legal/license.txt
 */
?>
<?php echo $this->getCleanProductPriceHtml(); ?>
<?php $product = $this->getProduct(); ?>
<?php $finalPrice = $product->getFinalPrice(1); ?>
<?php if ($product->canConfigure()): ?>
	<span class="price-label"><?php echo Mage::helper('wishlist')->__('Configured Price:') ?></span>
	<span class="price"><?php echo Mage::helper('core')->currency($finalPrice, true, false); ?></span>
<?php endif; ?>
